// Master header for drum samples
// Auto-generated by wav_to_c.py

#ifndef __DRUM_SAMPLES_H__
#define __DRUM_SAMPLES_H__

#include <stdint.h>
#include "drum_kick.h"
#include "drum_snare.h"
#include "drum_hihat.h"
#include "drum_floor.h"

// Array of drum samples for easy access
typedef struct {
    const int16_t *data;
    int len;
    const char *name;
} DrumSample;

static const DrumSample drum_samples[4] = {
    {drum_kick_data, drum_kick_len, "kick"},
    {drum_snare_data, drum_snare_len, "snare"},
    {drum_hihat_data, drum_hihat_len, "hihat"},
    {drum_floor_data, drum_floor_len, "floor"},
};

#endif // __DRUM_SAMPLES_H__
