/*
 * main.c  —  PICO SYNTH v1.0 (C / Pico SDK)
 * ==========================================
 * Hardware (from README + existing wiring):
 *   I2S audio  : PIO, BCLK=GP9  WS=GP10  DATA=GP11
 *   Keypad LEDs: SPI0, CS=GP17  SCK=GP6   MOSI=GP7   (APA102 / DotStar)
 *   Keypad btns: I2C0, SDA=GP4  SCL=GP5   (MCP23017 @ 0x20)
 *   Audio DAC  : I2C0, same bus               (TLV320DAC3100 @ 0x18)
 *   Pots       : ADC0=GP26(vol) ADC1=GP27(rate) ADC2=GP28(depth)
 *   Encoder    : GP12(CLK) GP21(DT) GP22(SW)
 *
 * Build:  mkdir build && cd build && cmake .. && make -j4
 * Flash:  hold BOOTSEL, plug USB, copy pico_synth.uf2 to RPI-RP2 drive
 */

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

#include "pico/stdlib.h"
#include "hardware/spi.h"
#include "hardware/i2c.h"
#include "hardware/adc.h"
#include "hardware/dma.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "hardware/irq.h"
#include "hardware/gpio.h"

#include "i2s.pio.h"      // generated by CMake from i2s.pio
#include "drum_samples.h" // generated by CMake from wav_to_c.py

// ── Pin definitions ───────────────────────────────────────────────────────────

#define PIN_I2S_DATA 11
#define PIN_I2S_BCLK 9 // LRCLK must be BCLK+1 = GP10
#define PIN_I2S_WS 10  // (checked at runtime: must equal PIN_I2S_BCLK+1)

#define SPI_KEYPAD spi0
#define PIN_APA_CS 17   // not used by APA102 but set high
#define PIN_APA_SCK 18  // Pimoroni Pico RGB Keypad SCK
#define PIN_APA_MOSI 19 // Pimoroni Pico RGB Keypad MOSI

#define I2C_BUS i2c0
#define PIN_I2C_SDA 4 // Pimoroni keypad I2C bus (GP4/GP5)
#define PIN_I2C_SCL 5

#define MCP_ADDR 0x20 // MCP23017 button IC
#define TLV_ADDR 0x18 // TLV320DAC3100 audio DAC

#define PIN_ENC_CLK 12
#define PIN_ENC_DT 21 // matches working MicroPython wiring
#define PIN_ENC_SW 22

// ADC channel numbers (avoid names that clash with Pico SDK hardware registers)
#define POT_CH_VOL 0   // GP26 = ADC0
#define POT_CH_RATE 1  // GP27 = ADC1
#define POT_CH_DEPTH 2 // GP28 = ADC2

// OLED (SH1106, I2C, shares I2C_BUS on GP4/GP5 — wire SDA→GP4, SCL→GP5)
#define OLED_ADDR 0x3C
#define OLED_W 128
#define OLED_H 64
#define OLED_PAGES 8 // 64 / 8

static uint8_t oled_addr = OLED_ADDR;

// Detected device flags (set during I2C scan, printed in debug loop)
static bool dev_found_tca = false;
static bool dev_found_tlv = false;
static bool dev_found_oled = false;

// Audio constants
//
// Note: DRUM_SAMPLES is now variable per sample (from drum_samples.h)
#define SAMPLE_RATE 16000
#define BUFFER_SIZE 256 // Larger buffer = better timing stability, lower jitter
#define MAX_VOICES 4

// ADSR — integer 0..32767, advanced once per buffer (256 samples @ 16kHz = 16ms)
#define SUSTAIN_INT 22937 //  0.7 × 32767
#define ATTACK_STEP 10485 // 50ms attack: 32767 / 3.1 buffers = snappy but smooth
#define DECAY_STEP 780    // 100ms decay
#define RELEASE_STEP 1400 // 400ms release for musicality

typedef enum
{
    ENV_IDLE,
    ENV_ATTACK,
    ENV_DECAY,
    ENV_SUSTAIN,
    ENV_RELEASE
} EnvState;

// ── Sine lookup (256 entries, int16_t) ────────────────────────────────────────

static int16_t sine_table[256];

// ── Per-voice state ───────────────────────────────────────────────────────────

static int v_pitch[MAX_VOICES];
static bool v_gate[MAX_VOICES];
static uint32_t v_phase1[MAX_VOICES];
static uint32_t v_phase2[MAX_VOICES];
static uint32_t v_inc1[MAX_VOICES];
static uint32_t v_inc2[MAX_VOICES];
static int32_t v_env[MAX_VOICES];
static EnvState v_state[MAX_VOICES];
static int voice_rr = 0;

// Dual oscillator params
static int osc2_coarse = 0; // semitone offset
static int osc2_fine = 7;   // fine detune units (≈ cents)
static int osc1_mix = 48;   // weights sum to 64
static int osc2_mix = 16;

// LFO
static uint32_t lfo_phase = 0;
static uint32_t lfo_inc = 0;
static int lfo_depth = 0;
static int32_t lfo_val = 0;

// Master output gain in Q8 fixed-point (256 = 1.0x, now set to 2.55x for 85% of previous 3.0x).
static int master_gain_q8 = 653;

// Drum state (using samples from drum_samples.h)
static const int16_t *active_drum = NULL;
static int active_drum_len = 0;
static int drum_pos = 0;

// Waveform: 0=sine 1=square 2=triangle 3=sawtooth
static int current_waveform = 0;

// ── DMA / I2S buffers ────────────────────────────────────────────────────────
// Each word = left(16-bit hi) | right(16-bit lo)

static uint32_t audio_buf[2][BUFFER_SIZE];
static volatile int dma_play_idx = 0; // buffer DMA is currently playing
static volatile bool need_fill = false;
static int dma_chan;
static PIO audio_pio;
static uint audio_sm;

// ── Key assignment data ───────────────────────────────────────────────────────

typedef enum
{
    KEY_DRUM,
    KEY_CHORD
} KeyType;

typedef struct
{
    KeyType type;
    int root;
    int intervals[4];
    int n_intervals;
} KeyAssign;

// Interval tables
static const int IV_MAJOR[3] = {0, 4, 7};
static const int IV_MINOR[3] = {0, 3, 7};
static const int IV_DOM7[4] = {0, 4, 7, 10};
static const int IV_MAJ7[4] = {0, 4, 7, 11};
static const int IV_MIN7[4] = {0, 3, 7, 10};
static const int IV_DIM[3] = {0, 3, 6};
static const int IV_AUG[3] = {0, 4, 8};
static const int IV_SUS2[3] = {0, 2, 7};
static const int IV_SUS4[3] = {0, 5, 7};

static KeyAssign key_assign[16];

// Per-key: which MIDI notes it triggered (for correct polyphonic release)
static int key_notes[16][4];
static int key_note_n[16];

// ── Debounce state ────────────────────────────────────────────────────────────

static uint16_t pressed_keys = 0; // confirmed held bitmask
static uint8_t press_count[16] = {0};
static uint8_t release_count[16] = {0};
#define PRESS_SCANS 2
#define RELEASE_SCANS 4

// ── OLED framebuffer ──────────────────────────────────────────────────────────

static uint8_t oled_buf[OLED_W * OLED_PAGES]; // 1024 bytes
static void oled_flush(void);                 // forward declaration

// ── Encoder state ─────────────────────────────────────────────────────────────

static int enc_last_clk = 1;
static bool enc_last_sw = true;
static uint32_t last_enc_ms = 0;

// ── Synthesis helpers ─────────────────────────────────────────────────────────

static uint32_t midi_to_inc(int midi_note)
{
    float freq = 440.0f * powf(2.0f, (midi_note - 69) / 12.0f);
    return (uint32_t)(freq * 16777216.0f / SAMPLE_RATE);
}

static uint32_t inc2_for(int midi_note)
{
    uint32_t base = midi_to_inc(midi_note + osc2_coarse);
    return base + (uint32_t)((uint64_t)base * osc2_fine >> 10);
}

// ── Voice management ──────────────────────────────────────────────────────────

static void voice_start(int v, int midi_note)
{
    v_pitch[v] = midi_note;
    v_gate[v] = true;
    v_phase1[v] = 0;
    v_phase2[v] = 0;
    v_inc1[v] = midi_to_inc(midi_note);
    v_inc2[v] = inc2_for(midi_note);
    v_env[v] = 0;
    v_state[v] = ENV_ATTACK;
}

static void note_on(int midi_note)
{
    // If already playing and sustaining, leave envelope alone
    for (int v = 0; v < MAX_VOICES; v++)
    {
        if (v_gate[v] && v_pitch[v] == midi_note)
        {
            if (v_state[v] == ENV_IDLE || v_state[v] == ENV_RELEASE)
            {
                v_env[v] = 0;
                v_state[v] = ENV_ATTACK;
            }
            return;
        }
    }
    // Use idle voice
    for (int v = 0; v < MAX_VOICES; v++)
    {
        if (v_state[v] == ENV_IDLE)
        {
            voice_start(v, midi_note);
            return;
        }
    }
    // Round-robin steal
    voice_start(voice_rr, midi_note);
    voice_rr = (voice_rr + 1) % MAX_VOICES;
}

static void note_off(int midi_note)
{
    for (int v = 0; v < MAX_VOICES; v++)
    {
        if (v_gate[v] && v_pitch[v] == midi_note)
        {
            v_gate[v] = false;
            if (v_state[v] != ENV_IDLE)
                v_state[v] = ENV_RELEASE;
        }
    }
}

// ── Key press / release ───────────────────────────────────────────────────────

static void key_press(int k)
{
    KeyAssign *a = &key_assign[k];
    if (a->type == KEY_DRUM)
        return; // drums handled separately

    int n = a->n_intervals;
    key_note_n[k] = n;
    for (int i = 0; i < n; i++)
    {
        int note = a->root + a->intervals[i];
        key_notes[k][i] = note;
        note_on(note);
    }
}

static void key_release(int k)
{
    // Build set of notes still held by other keys
    bool still_held[128] = {false};
    for (int j = 0; j < 16; j++)
    {
        if (j == k)
            continue;
        if (!(pressed_keys & (1 << j)))
            continue;
        for (int i = 0; i < key_note_n[j]; i++)
            still_held[key_notes[j][i]] = true;
    }
    for (int i = 0; i < key_note_n[k]; i++)
    {
        int note = key_notes[k][i];
        if (!still_held[note])
            note_off(note);
    }
    key_note_n[k] = 0;
}

// ── Audio fill ────────────────────────────────────────────────────────────────

static void fill_audio_buffer(uint32_t *buf)
{
    // Advance LFO (triangle wave)
    lfo_phase = (lfo_phase + lfo_inc) & 0xFFFFFF;
    int lp = (lfo_phase >> 16) & 255;
    if (lp < 64)
        lfo_val = (int32_t)lp * 512;
    else if (lp < 128)
        lfo_val = (int32_t)(127 - lp) * 512;
    else if (lp < 192)
        lfo_val = -(int32_t)(lp - 128) * 512;
    else
        lfo_val = -(int32_t)(255 - lp) * 512;

    // Advance per-voice ADSR
    for (int v = 0; v < MAX_VOICES; v++)
    {
        switch (v_state[v])
        {
        case ENV_ATTACK:
            v_env[v] += ATTACK_STEP;
            if (v_env[v] >= 32767)
            {
                v_env[v] = 32767;
                v_state[v] = ENV_DECAY;
            }
            break;
        case ENV_DECAY:
            v_env[v] -= DECAY_STEP;
            if (v_env[v] <= SUSTAIN_INT)
            {
                v_env[v] = SUSTAIN_INT;
                v_state[v] = ENV_SUSTAIN;
            }
            break;
        case ENV_RELEASE:
            v_env[v] -= RELEASE_STEP;
            if (v_env[v] <= 0)
            {
                v_env[v] = 0;
                v_state[v] = ENV_IDLE;
            }
            break;
        default:
            break;
        }
    }

    // Check if anything to render
    bool any_voice = false;
    for (int v = 0; v < MAX_VOICES; v++)
        if (v_state[v] != ENV_IDLE)
        {
            any_voice = true;
            break;
        }
    bool has_drum = (active_drum != NULL);

    if (!any_voice && !has_drum)
    {
        memset(buf, 0, BUFFER_SIZE * sizeof(uint32_t));
        return;
    }

    // Pre-compute LFO-modulated increments
    uint32_t im1[MAX_VOICES], im2[MAX_VOICES];
    for (int v = 0; v < MAX_VOICES; v++)
    {
        if (v_state[v] != ENV_IDLE && lfo_depth > 0)
        {
            int64_t mod1 = ((int64_t)v_inc1[v] * lfo_val >> 20) * lfo_depth >> 6;
            int64_t mod2 = ((int64_t)v_inc2[v] * lfo_val >> 20) * lfo_depth >> 6;
            im1[v] = (uint32_t)((int64_t)v_inc1[v] + mod1);
            im2[v] = (uint32_t)((int64_t)v_inc2[v] + mod2);
        }
        else
        {
            im1[v] = v_inc1[v];
            im2[v] = v_inc2[v];
        }
    }

    for (int i = 0; i < BUFFER_SIZE; i++)
    {
        int32_t cs = 0;

        for (int v = 0; v < MAX_VOICES; v++)
        {
            if (v_state[v] == ENV_IDLE)
                continue;
            int32_t ea = v_env[v];

            // OSC1
            int pb1 = (int)((v_phase1[v] >> 16) & 255);
            int32_t s1;
            switch (current_waveform)
            {
            case 0:
                s1 = sine_table[pb1];
                break;
            case 1:
                s1 = pb1 < 128 ? 32767 : -32767;
                break;
            case 2:
                s1 = pb1 < 128 ? (pb1 * 516 - 32767) : ((255 - pb1) * 516 - 32767);
                break;
            default:
                s1 = pb1 * 256 - 32768;
                break;
            }
            v_phase1[v] += im1[v]; // Use full 32-bit precision (natural wraparound)

            // OSC2
            int pb2 = (int)((v_phase2[v] >> 16) & 255);
            int32_t s2;
            switch (current_waveform)
            {
            case 0:
                s2 = sine_table[pb2];
                break;
            case 1:
                s2 = pb2 < 128 ? 32767 : -32767;
                break;
            case 2:
                // Triangle: proper ramp up/down with correct scaling
                s2 = pb2 < 128 ? ((pb2 << 9) - 32767) : ((32767 - (pb2 - 128) * 512));
                break;
            default:
                // Sawtooth: -32768 to +32767
                s2 = (pb2 << 8) - 32768;
                break;
            }
            v_phase2[v] += im2[v]; // Use full 32-bit precision (natural wraparound)

            // Mix + envelope: >>23 = /64 (mix) /32767 (env norm) /4 (voice headroom)
            cs += (int32_t)(((int64_t)(s1 * osc1_mix + s2 * osc2_mix) * ea) >> 23);
        }

        // Drum (scale to 95% for good presence without excessive clipping)
        int32_t ds = 0;
        if (has_drum)
        {
            ds = (active_drum[drum_pos++] * 498072) >> 16; // 8x scaling
            if (drum_pos >= active_drum_len)
            {
                active_drum = NULL;
                has_drum = false;
            }
        }

        int32_t s = cs + ds;

        // Apply master gain from volume pot. Above 100% is allowed via
        // master_gain_q8 and shaped by the soft limiter below.
        s = (int32_t)(((int64_t)s * master_gain_q8) >> 8);

        // Soft-knee limiter: gently compress above ~73% FS to reduce harsh clip.
        int32_t a = s >= 0 ? s : -s;
        if (a > 24000)
        {
            int32_t excess = a - 24000;
            a = 24000 + (excess >> 2); // 4:1 compression above knee
            if (a > 32767)
                a = 32767;
            s = s >= 0 ? a : -a;
        }

        if (s > 32767)
            s = 32767;
        if (s < -32768)
            s = -32768;

        // Pack as 32-bit word: left in high 16, right in low 16
        uint16_t u = (uint16_t)(int16_t)s;
        buf[i] = ((uint32_t)u << 16) | u;
    }
}

// ── DMA interrupt ─────────────────────────────────────────────────────────────

static void dma_irq_handler(void)
{
    dma_hw->ints0 = 1u << dma_chan;

    // Restart DMA on the just-finished buffer index (now "next to fill")
    int fill_buf = dma_play_idx;
    dma_play_idx ^= 1;

    // Point DMA at the other buffer (the one we just swapped to)
    dma_channel_set_read_addr(dma_chan, audio_buf[dma_play_idx], true);

    // Signal main loop to fill fill_buf
    // We use a simple flag; fill_audio_buffer() is called from main()
    (void)fill_buf; // main reads dma_play_idx ^ 1 to know which to fill
    need_fill = true;
}

// ── I2S / DMA setup ───────────────────────────────────────────────────────────

static void i2s_dma_init(void)
{
    audio_pio = pio0;
    uint offset = pio_add_program(audio_pio, &i2s_out_program);
    audio_sm = pio_claim_unused_sm(audio_pio, true);

    i2s_out_program_init(audio_pio, audio_sm, offset,
                         PIN_I2S_DATA, PIN_I2S_BCLK, SAMPLE_RATE);

    // Zero out both buffers
    memset(audio_buf, 0, sizeof(audio_buf));

    dma_chan = dma_claim_unused_channel(true);
    dma_channel_config cfg = dma_channel_get_default_config(dma_chan);
    channel_config_set_transfer_data_size(&cfg, DMA_SIZE_32);
    channel_config_set_read_increment(&cfg, true);
    channel_config_set_write_increment(&cfg, false);
    channel_config_set_dreq(&cfg, pio_get_dreq(audio_pio, audio_sm, true));

    dma_channel_configure(dma_chan, &cfg,
                          &audio_pio->txf[audio_sm], // write to PIO TX FIFO
                          audio_buf[0],              // read from buffer 0
                          BUFFER_SIZE,
                          false);

    dma_channel_set_irq0_enabled(dma_chan, true);
    irq_set_exclusive_handler(DMA_IRQ_0, dma_irq_handler);
    irq_set_enabled(DMA_IRQ_0, true);

    dma_play_idx = 0;
    dma_channel_start(dma_chan);
}

// ── TLV320DAC3100 init ────────────────────────────────────────────────────────

static void tlv_write(uint8_t reg, uint8_t val)
{
    uint8_t buf[2] = {reg, val};
    i2c_write_blocking(I2C_BUS, TLV_ADDR, buf, 2, false);
}

static void tlv_init(void)
{
    // Page 0
    tlv_write(0x00, 0x00); // select page 0
    tlv_write(0x01, 0x01); // software reset
    sleep_ms(10);

    // I2S slave mode, 16-bit word length
    // Reg 27: bit7=BCLK_OUT=0(input), bit6=WS_OUT=0(input), bits5:4=00(I2S), bits1:0=00(16-bit)
    tlv_write(0x1B, 0x00);

    // Power up DAC: left + right powered, softstepping enabled
    tlv_write(0x3F, 0xD4); // reg 63: power up L+R DAC, soft-step 1/fs
    tlv_write(0x40, 0x00); // reg 64: left data→left DAC, right data→right DAC
    tlv_write(0x41, 0x00); // reg 65: left DAC digital volume = 0 dB
    tlv_write(0x42, 0x00); // reg 66: right DAC digital volume = 0 dB

    // Page 1: output driver config
    tlv_write(0x00, 0x01); // select page 1
    tlv_write(0x01, 0x08); // reg 1: AVDD/DVDD scheme
    sleep_ms(10);
    tlv_write(0x09, 0x3C); // reg 9:  power up HPL driver
    tlv_write(0x0A, 0x3C); // reg 10: power up HPR driver
    tlv_write(0x0C, 0x08); // reg 12: route DAC_L to HPL
    tlv_write(0x0D, 0x08); // reg 13: route DAC_R to HPR

    tlv_write(0x00, 0x00); // back to page 0
    printf("TLV320DAC3100 ready\n");
}

// ── Pimoroni RGB Keypad LEDs (APA102 / DotStar) ───────────────────────────────
// 16 LEDs — send start frame, 16 LED frames, end frame

static uint8_t led_r[16], led_g[16], led_b[16];
// APA102 global brightness: 1..31 (lower = dimmer). 8 is a good low-power default.
static const uint8_t LED_GLOBAL_BRIGHTNESS = 1;

static void apa102_send_byte(uint8_t byte)
{
    spi_write_blocking(SPI_KEYPAD, &byte, 1);
}

static void update_leds(void)
{
    // Pimoroni keypad latches LED data with CS framing.
    gpio_put(PIN_APA_CS, 0);
    // Start frame
    for (int i = 0; i < 4; i++)
        apa102_send_byte(0x00);
    // LED frames: 0b111xxxxx brightness header, then B, G, R
    for (int i = 0; i < 16; i++)
    {
        apa102_send_byte((uint8_t)(0xE0 | (LED_GLOBAL_BRIGHTNESS & 0x1F)));
        apa102_send_byte(led_b[i]);
        apa102_send_byte(led_g[i]);
        apa102_send_byte(led_r[i]);
    }
    // End frame (need N/2 clocks for 16 LEDs → 1 byte min, send 4)
    for (int i = 0; i < 4; i++)
        apa102_send_byte(0xFF);
    gpio_put(PIN_APA_CS, 1);
}

static void set_led(int k, uint8_t r, uint8_t g, uint8_t b)
{
    led_r[k] = r;
    led_g[k] = g;
    led_b[k] = b;
}

// Chord type → LED color
static void chord_color(const int *ivs, int n, uint8_t *r, uint8_t *g, uint8_t *b)
{
    int i1 = n > 1 ? ivs[1] : -1;
    int i2 = n > 2 ? ivs[2] : -1;
    int i3 = n > 3 ? ivs[3] : -1;
    if (i1 == 4 && i2 == 7 && i3 == -1)
    {
        *r = 0;
        *g = 32;
        *b = 0;
        return;
    } // Major  green
    if (i1 == 3 && i2 == 7 && i3 == -1)
    {
        *r = 0;
        *g = 0;
        *b = 32;
        return;
    } // Minor  blue
    if (i1 == 3 && i2 == 6)
    {
        *r = 20;
        *g = 0;
        *b = 32;
        return;
    } // Dim    purple
    if (i1 == 4 && i2 == 8)
    {
        *r = 32;
        *g = 12;
        *b = 0;
        return;
    } // Aug    orange
    if (i1 == 2 && i2 == 7)
    {
        *r = 0;
        *g = 28;
        *b = 32;
        return;
    } // Sus2   cyan
    if (i1 == 5 && i2 == 7)
    {
        *r = 0;
        *g = 28;
        *b = 32;
        return;
    } // Sus4   cyan
    if (i3 == 11)
    {
        *r = 32;
        *g = 28;
        *b = 0;
        return;
    } // Maj7   yellow
    if (i3 == 10)
    {
        *r = 32;
        *g = 28;
        *b = 0;
        return;
    } // Dom7   yellow
    *r = 16;
    *g = 16;
    *b = 16;
}

static void refresh_leds(void)
{
    for (int k = 0; k < 16; k++)
    {
        if (pressed_keys & (1 << k))
        {
            set_led(k, 64, 64, 64); // bright white = held
        }
        else
        {
            KeyAssign *a = &key_assign[k];
            if (a->type == KEY_DRUM)
            {
                set_led(k, 22, 22, 22);
            }
            else
            {
                uint8_t r, g, b;
                chord_color(a->intervals, a->n_intervals, &r, &g, &b);
                set_led(k, r, g, b);
            }
        }
    }
    update_leds();
}

static void led_self_test(void)
{
    for (int i = 0; i < 16; i++)
        set_led(i, 0, 0, 0);
    update_leds();
    sleep_ms(80);

    for (int i = 0; i < 16; i++)
        set_led(i, 120, 0, 0);
    update_leds();
    sleep_ms(120);

    for (int i = 0; i < 16; i++)
        set_led(i, 0, 120, 0);
    update_leds();
    sleep_ms(120);

    for (int i = 0; i < 16; i++)
        set_led(i, 0, 0, 120);
    update_leds();
    sleep_ms(120);
}

// ── TCA9555 button reading ────────────────────────────────────────────────────
// Pimoroni RGB Keypad uses TCA9555 (not MCP23017). Register map:
//   0x00 / 0x01 = Input Port 0/1  (read buttons here)
//   0x06 / 0x07 = Config Port 0/1 (1=input, default 0xFF — all inputs)

static void mcp_write(uint8_t reg, uint8_t val)
{
    uint8_t buf[2] = {reg, val};
    i2c_write_blocking(I2C_BUS, MCP_ADDR, buf, 2, false);
}

static uint8_t mcp_read(uint8_t reg)
{
    i2c_write_blocking(I2C_BUS, MCP_ADDR, &reg, 1, true);
    uint8_t val;
    i2c_read_blocking(I2C_BUS, MCP_ADDR, &val, 1, false);
    return val;
}

static void mcp_init(void)
{
    // TCA9555 defaults to all-input mode; write config regs explicitly anyway
    mcp_write(0x06, 0xFF); // Config Port 0: all inputs
    mcp_write(0x07, 0xFF); // Config Port 1: all inputs
    printf("TCA9555 ready\n");
}

// Returns 16-bit bitmask of raw button states (1 = pressed, active low inverted)
static uint16_t mcp_read_buttons(void)
{
    uint8_t a = ~mcp_read(0x00); // Input Port 0, invert (pressed=low → 1)
    uint8_t b = ~mcp_read(0x01); // Input Port 1
    return (uint16_t)a | ((uint16_t)b << 8);
}

// ── SH1106 OLED driver (I2C, page-addressed) ─────────────────────────────────

// 5×7 font, 5 bytes per glyph, each byte = column (bit 0 = topmost row)
// Covers ASCII 0x20 ' ' through 0x5A 'Z'
static const uint8_t font5x7[][5] = {
    {0x00, 0x00, 0x00, 0x00, 0x00}, // ' '
    {0x00, 0x00, 0x5F, 0x00, 0x00}, // '!'
    {0x00, 0x07, 0x00, 0x07, 0x00}, // '"'
    {0x14, 0x7F, 0x14, 0x7F, 0x14}, // '#'
    {0x24, 0x2A, 0x7F, 0x2A, 0x12}, // '$'
    {0x23, 0x13, 0x08, 0x64, 0x62}, // '%'
    {0x36, 0x49, 0x55, 0x22, 0x50}, // '&'
    {0x00, 0x05, 0x03, 0x00, 0x00}, // '\''
    {0x00, 0x1C, 0x22, 0x41, 0x00}, // '('
    {0x00, 0x41, 0x22, 0x1C, 0x00}, // ')'
    {0x14, 0x08, 0x3E, 0x08, 0x14}, // '*'
    {0x08, 0x08, 0x3E, 0x08, 0x08}, // '+'
    {0x00, 0x50, 0x30, 0x00, 0x00}, // ','
    {0x08, 0x08, 0x08, 0x08, 0x08}, // '-'
    {0x00, 0x60, 0x60, 0x00, 0x00}, // '.'
    {0x20, 0x10, 0x08, 0x04, 0x02}, // '/'
    {0x3E, 0x51, 0x49, 0x45, 0x3E}, // '0'
    {0x00, 0x42, 0x7F, 0x40, 0x00}, // '1'
    {0x42, 0x61, 0x51, 0x49, 0x46}, // '2'
    {0x21, 0x41, 0x45, 0x4B, 0x31}, // '3'
    {0x18, 0x14, 0x12, 0x7F, 0x10}, // '4'
    {0x27, 0x45, 0x45, 0x45, 0x39}, // '5'
    {0x3C, 0x4A, 0x49, 0x49, 0x30}, // '6'
    {0x01, 0x71, 0x09, 0x05, 0x03}, // '7'
    {0x36, 0x49, 0x49, 0x49, 0x36}, // '8'
    {0x06, 0x49, 0x49, 0x29, 0x1E}, // '9'
    {0x00, 0x36, 0x36, 0x00, 0x00}, // ':'
    {0x00, 0x56, 0x36, 0x00, 0x00}, // ';'
    {0x08, 0x14, 0x22, 0x41, 0x00}, // '<'
    {0x14, 0x14, 0x14, 0x14, 0x14}, // '='
    {0x00, 0x41, 0x22, 0x14, 0x08}, // '>'
    {0x02, 0x01, 0x51, 0x09, 0x06}, // '?'
    {0x32, 0x49, 0x79, 0x41, 0x3E}, // '@'
    {0x7E, 0x11, 0x11, 0x11, 0x7E}, // 'A'
    {0x7F, 0x49, 0x49, 0x49, 0x36}, // 'B'
    {0x3E, 0x41, 0x41, 0x41, 0x22}, // 'C'
    {0x7F, 0x41, 0x41, 0x22, 0x1C}, // 'D'
    {0x7F, 0x49, 0x49, 0x49, 0x41}, // 'E'
    {0x7F, 0x09, 0x09, 0x01, 0x01}, // 'F'
    {0x3E, 0x41, 0x49, 0x49, 0x7A}, // 'G'
    {0x7F, 0x08, 0x08, 0x08, 0x7F}, // 'H'
    {0x00, 0x41, 0x7F, 0x41, 0x00}, // 'I'
    {0x20, 0x40, 0x41, 0x3F, 0x01}, // 'J'
    {0x7F, 0x08, 0x14, 0x22, 0x41}, // 'K'
    {0x7F, 0x40, 0x40, 0x40, 0x40}, // 'L'
    {0x7F, 0x02, 0x0C, 0x02, 0x7F}, // 'M'
    {0x7F, 0x04, 0x08, 0x10, 0x7F}, // 'N'
    {0x3E, 0x41, 0x41, 0x41, 0x3E}, // 'O'
    {0x7F, 0x09, 0x09, 0x09, 0x06}, // 'P'
    {0x3E, 0x41, 0x51, 0x21, 0x5E}, // 'Q'
    {0x7F, 0x09, 0x19, 0x29, 0x46}, // 'R'
    {0x46, 0x49, 0x49, 0x49, 0x31}, // 'S'
    {0x01, 0x01, 0x7F, 0x01, 0x01}, // 'T'
    {0x3F, 0x40, 0x40, 0x40, 0x3F}, // 'U'
    {0x1F, 0x20, 0x40, 0x20, 0x1F}, // 'V'
    {0x3F, 0x40, 0x38, 0x40, 0x3F}, // 'W'
    {0x63, 0x14, 0x08, 0x14, 0x63}, // 'X'
    {0x07, 0x08, 0x70, 0x08, 0x07}, // 'Y'
    {0x61, 0x51, 0x49, 0x45, 0x43}, // 'Z'
};

static void oled_cmd(uint8_t c)
{
    uint8_t buf[2] = {0x00, c};
    i2c_write_blocking(I2C_BUS, oled_addr, buf, 2, false);
}

static bool i2c_addr_present(uint8_t addr)
{
    uint8_t dummy;
    return i2c_read_blocking(I2C_BUS, addr, &dummy, 1, false) >= 0;
}

static void oled_init(void)
{
    if (i2c_addr_present(0x3C))
        oled_addr = 0x3C;
    else if (i2c_addr_present(0x3D))
        oled_addr = 0x3D;
    else
    {
        printf("OLED not found at 0x3C/0x3D\n");
        return;
    }

    sleep_ms(100);  // give OLED power rail time to stabilize
    oled_cmd(0xAE); // display off
    oled_cmd(0xD5);
    oled_cmd(0x80); // clock divide ratio / osc freq
    oled_cmd(0xA8);
    oled_cmd(0x3F); // multiplex ratio = 64
    oled_cmd(0xD3);
    oled_cmd(0x00); // display offset = 0
    oled_cmd(0x40); // display start line = 0
    oled_cmd(0xAD);
    oled_cmd(0x8B); // charge pump: internal VCC  ← SH1106 specific
    oled_cmd(0x32); // charge pump voltage: 9V             ← SH1106 specific
    oled_cmd(0xA1); // segment re-map: col 131 → SEG0 (mirror)
    oled_cmd(0xC8); // COM scan direction: remapped
    oled_cmd(0xDA);
    oled_cmd(0x12); // COM pins hardware config
    oled_cmd(0x81);
    oled_cmd(0xCF); // contrast
    oled_cmd(0xD9);
    oled_cmd(0x1F); // pre-charge period  ← was 0xF1, wrong for internal pump
    oled_cmd(0xDB);
    oled_cmd(0x40); // VCOM deselect level
    oled_cmd(0xA4); // output follows RAM (not all-on)
    oled_cmd(0xA6); // normal display (not inverted)
    sleep_ms(10);
    oled_cmd(0xAF); // display ON
    sleep_ms(10);
    memset(oled_buf, 0, sizeof(oled_buf));
    oled_flush(); // push blank frame before printing ready
    printf("OLED ready at 0x%02X\n", oled_addr);
}

// Set a single pixel in the framebuffer
static void oled_pixel(int x, int y, bool on)
{
    if ((unsigned)x >= OLED_W || (unsigned)y >= OLED_H)
        return;
    int page = y >> 3;
    int bit = y & 7;
    if (on)
        oled_buf[page * OLED_W + x] |= (uint8_t)(1 << bit);
    else
        oled_buf[page * OLED_W + x] &= ~(uint8_t)(1 << bit);
}

// Draw a character at pixel position (x, y). Returns new x.
static int oled_char(int x, int y, char c)
{
    if (c < ' ' || c > 'Z')
        c = ' ';
    const uint8_t *g = font5x7[(uint8_t)(c - ' ')];
    for (int col = 0; col < 5; col++)
    {
        uint8_t bits = g[col];
        for (int row = 0; row < 7; row++)
        {
            if (bits & (1 << row))
                oled_pixel(x + col, y + row, true);
        }
    }
    return x + 6; // 5px glyph + 1px gap
}

static void oled_str(int x, int y, const char *s)
{
    while (*s)
        x = oled_char(x, y, *s++);
}

// Push framebuffer to display (SH1106 page-addressed, 2-col offset)
static void oled_flush(void)
{
    uint8_t row_buf[129];
    row_buf[0] = 0x40; // Co=0, D/C#=1 → data stream
    for (int pg = 0; pg < OLED_PAGES; pg++)
    {
        oled_cmd(0xB0 + pg); // set page address
        oled_cmd(0x02);      // column low  nibble = 2 (SH1106 2-col offset, low  nibble)
        oled_cmd(0x10);      // column high nibble = 0 (high nibble command = 0x10 + 0)
        memcpy(row_buf + 1, oled_buf + pg * OLED_W, OLED_W);
        i2c_write_blocking(I2C_BUS, oled_addr, row_buf, 129, false);
    }
}

// Generate a 4-char label string for key k
static void key_label(int k, char out[5])
{
    static const char *drum_names[8] = {
        "KICK", "SNAR", "HHAT", "CLAP", "TOM1", "TOM2", "TOM3", "CYMB"};
    static const char *note_names[12] = {
        "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"};
    KeyAssign *a = &key_assign[k];
    if (a->type == KEY_DRUM)
    {
        memcpy(out, drum_names[a->root % 8], 4);
        out[4] = '\0';
        return;
    }
    // Chord: root note + type abbreviation
    const char *note = note_names[a->root % 12];
    const char *ctype = "??? ";
    if (a->n_intervals == 3 && a->intervals[1] == 4 && a->intervals[2] == 7)
        ctype = "MAJ";
    else if (a->n_intervals == 3 && a->intervals[1] == 3 && a->intervals[2] == 7)
        ctype = "MIN";
    else if (a->n_intervals == 3 && a->intervals[1] == 3 && a->intervals[2] == 6)
        ctype = "DIM";
    else if (a->n_intervals == 3 && a->intervals[1] == 4 && a->intervals[2] == 8)
        ctype = "AUG";
    else if (a->n_intervals == 3 && a->intervals[1] == 2 && a->intervals[2] == 7)
        ctype = "SS2";
    else if (a->n_intervals == 3 && a->intervals[1] == 5 && a->intervals[2] == 7)
        ctype = "SS4";
    else if (a->n_intervals == 4 && a->intervals[3] == 10)
        ctype = "DM7";
    else if (a->n_intervals == 4 && a->intervals[3] == 11 && a->intervals[1] == 4)
        ctype = "MM7";
    else if (a->n_intervals == 4 && a->intervals[3] == 10 && a->intervals[1] == 3)
        ctype = "MN7";
    snprintf(out, 5, "%s%s", note, ctype);
}

// Draw the 4×4 key grid into oled_buf
static void draw_grid(void)
{
    memset(oled_buf, 0, sizeof(oled_buf));
    // Grid lines
    for (int y = 0; y < OLED_H; y++)
    {
        oled_pixel(0, y, true);
        oled_pixel(31, y, true);
        oled_pixel(63, y, true);
        oled_pixel(95, y, true);
        oled_pixel(127, y, true);
    }
    for (int x = 0; x < OLED_W; x++)
    {
        oled_pixel(x, 0, true);
        oled_pixel(x, 15, true);
        oled_pixel(x, 31, true);
        oled_pixel(x, 47, true);
        oled_pixel(x, 63, true);
    }
    // Labels and press highlights
    char label[5];
    for (int row = 0; row < 4; row++)
    {
        for (int col = 0; col < 4; col++)
        {
            int k = row * 4 + col;
            int cx = col * 32; // cell left edge (= border pixel)
            int cy = row * 16; // cell top edge  (= border pixel)
            // Invert cell background if key is held
            if (pressed_keys & (1 << k))
            {
                for (int px = cx + 1; px < cx + 31; px++)
                    for (int py = cy + 1; py < cy + 15; py++)
                        oled_pixel(px, py, true);
            }
            key_label(k, label);
            // Clip label to 4 chars, uppercase only
            for (int i = 0; i < 4 && label[i]; i++)
                if (label[i] >= 'a' && label[i] <= 'z')
                    label[i] -= 32;
            label[4] = '\0';
            int lw = (int)strlen(label) * 6 - 1;
            int tx = cx + 1 + (30 - lw) / 2; // centered in 30px inner width
            int ty = cy + 4;                 // 4px from top (7px font in 14px)
            // If inverted, draw in "off" pixels so text is dark on bright bg
            if (pressed_keys & (1 << k))
            {
                for (int c2 = 0; label[c2]; c2++)
                {
                    if (label[c2] < ' ' || label[c2] > 'Z')
                    {
                        tx += 6;
                        continue;
                    }
                    const uint8_t *g = font5x7[(uint8_t)(label[c2] - ' ')];
                    for (int fc = 0; fc < 5; fc++)
                        for (int fr = 0; fr < 7; fr++)
                            if (g[fc] & (1 << fr))
                                oled_pixel(tx + fc, ty + fr, false);
                    tx += 6;
                }
            }
            else
            {
                oled_str(tx, ty, label);
            }
        }
    }
}

// ── Drum synthesis ────────────────────────────────────────────────────────────

// ── Default key layout ────────────────────────────────────────────────────────

static void make_chord(KeyAssign *a, int root, const int *ivs, int n)
{
    a->type = KEY_CHORD;
    a->root = root;
    a->n_intervals = n;
    memcpy(a->intervals, ivs, n * sizeof(int));
}

static void setup_default_layout(void)
{
    // Row 0: drums
    for (int i = 0; i < 4; i++)
    {
        key_assign[i].type = KEY_DRUM;
        key_assign[i].root = i;
    }
    // Row 1: C D E F Major
    make_chord(&key_assign[4], 60, IV_MAJOR, 3);
    make_chord(&key_assign[5], 62, IV_MAJOR, 3);
    make_chord(&key_assign[6], 64, IV_MAJOR, 3);
    make_chord(&key_assign[7], 65, IV_MAJOR, 3);
    // Row 2: C D E F Minor (octave lower)
    make_chord(&key_assign[8], 48, IV_MINOR, 3);
    make_chord(&key_assign[9], 50, IV_MINOR, 3);
    make_chord(&key_assign[10], 52, IV_MINOR, 3);
    make_chord(&key_assign[11], 53, IV_MINOR, 3);
    // Row 3: mixed
    make_chord(&key_assign[12], 67, IV_MAJOR, 3);
    make_chord(&key_assign[13], 69, IV_MINOR, 3);
    make_chord(&key_assign[14], 71, IV_DIM, 3);
    make_chord(&key_assign[15], 72, IV_MAJ7, 4);
}

// ── ADC pot reading ───────────────────────────────────────────────────────────

// Returns 0..100 for volume, 2..8 for vib_rate, 0..50 for vib_depth
static void read_pots(int *vol, int *vib_rate, int *vib_depth)
{
    adc_select_input(POT_CH_VOL);
    int v = (int)(adc_read() * 100 / 4095);
    *vol = v < 0 ? 0 : (v > 100 ? 100 : v);

    adc_select_input(POT_CH_RATE);
    v = 2 + (int)(adc_read() * 6 / 4095);
    *vib_rate = v < 2 ? 2 : (v > 8 ? 8 : v);

    adc_select_input(POT_CH_DEPTH);
    v = (int)(adc_read() * 50 / 4095);
    *vib_depth = v < 0 ? 0 : (v > 50 ? 50 : v);
}

// ── Encoder reading ───────────────────────────────────────────────────────────

// Returns -1, 0, or +1 for rotation; sets *pressed if button newly pressed
static int read_encoder(bool *pressed)
{
    int clk = gpio_get(PIN_ENC_CLK);
    int rot = 0;
    if (clk != enc_last_clk)
    {
        if (clk == 0)
            rot = gpio_get(PIN_ENC_DT) ? 1 : -1;
        enc_last_clk = clk;
    }

    bool sw = gpio_get(PIN_ENC_SW);
    *pressed = false;
    if (!sw && enc_last_sw)
    {
        uint32_t now = to_ms_since_boot(get_absolute_time());
        if (now - last_enc_ms > 300)
        {
            *pressed = true;
            last_enc_ms = now;
        }
    }
    enc_last_sw = sw;
    return rot;
}

// ── Main ──────────────────────────────────────────────────────────────────────

int main(void)
{
    stdio_init_all();
    sleep_ms(2000);
    // If USB serial is connected, allow a brief pause for interactive boot.
    // Continue automatically so the synth still starts when running standalone.
    printf("Press any key to boot (auto-continue in 2s)...\n");
    int ch = getchar_timeout_us(2000000);
    if (ch == PICO_ERROR_TIMEOUT)
        printf("No serial input detected, continuing boot.\n");
    printf("=== PICO SYNTH v1.0 (C) ===\n");

    // ── Sine table ────────────────────────────────────────────────────────
    for (int i = 0; i < 256; i++)
        sine_table[i] = (int16_t)(sinf(2.0f * (float)M_PI * i / 256.0f) * 32767.0f);

    // ── Drum tables ───────────────────────────────────────────────────────
    printf("Drum samples compiled in from audio files\n");
    printf("Drums ready\n");

    // ── Voice init ────────────────────────────────────────────────────────
    memset(v_state, ENV_IDLE, sizeof(v_state));
    memset(v_gate, 0, sizeof(v_gate));

    // ── I2C init (keypad + TLV320) ────────────────────────────────────────
    // 400 kHz (fast mode) for lower latency — button/LED polling can saturate bus
    i2c_init(I2C_BUS, 400 * 1000);
    gpio_set_function(PIN_I2C_SDA, GPIO_FUNC_I2C);
    gpio_set_function(PIN_I2C_SCL, GPIO_FUNC_I2C);
    gpio_pull_up(PIN_I2C_SDA);
    gpio_pull_up(PIN_I2C_SCL);

    // ── TLV320 DAC init ───────────────────────────────────────────────────
    tlv_init();

    // ── I2S + DMA ─────────────────────────────────────────────────────────
    i2s_dma_init();
    printf("I2S DMA ready\n");

    // ── Keypad LEDs (APA102 via SPI0, Pimoroni pinout) ───────────────────
    spi_init(SPI_KEYPAD, 4 * 1000 * 1000);
    gpio_set_function(PIN_APA_SCK, GPIO_FUNC_SPI);
    gpio_set_function(PIN_APA_MOSI, GPIO_FUNC_SPI);
    gpio_init(PIN_APA_CS);
    gpio_set_dir(PIN_APA_CS, GPIO_OUT);
    gpio_put(PIN_APA_CS, 1);

    // ── Keypad buttons (TCA9555 via I2C0) ────────────────────────────────
    mcp_init();

    // ── OLED display (SH1106 via I2C0 — wire SDA→GP4, SCL→GP5) ──────────
    oled_init();

    // ── I2C bus scan (after init so all devices are settled) ─────────────
    printf("I2C scan (SDA=GP%d SCL=GP%d):\n", PIN_I2C_SDA, PIN_I2C_SCL);
    for (int addr = 0x08; addr < 0x78; addr++)
    {
        uint8_t rxdata;
        int ret = i2c_read_blocking(I2C_BUS, addr, &rxdata, 1, false);
        if (ret >= 0)
        {
            printf("  found 0x%02X\n", addr);
            if (addr == MCP_ADDR)
                dev_found_tca = true;
            if (addr == TLV_ADDR)
                dev_found_tlv = true;
            if (addr == 0x3C || addr == 0x3D)
                dev_found_oled = true;
        }
    }
    printf("I2C scan done  TCA=%d TLV=%d OLED=%d\n",
           dev_found_tca, dev_found_tlv, dev_found_oled);

    // ── ADC ───────────────────────────────────────────────────────────────
    adc_init();
    adc_gpio_init(26); // ADC0 = GP26 (volume)
    adc_gpio_init(27); // ADC1 = GP27 (vib rate)
    adc_gpio_init(28); // ADC2 = GP28 (vib depth)

    // ── Encoder ───────────────────────────────────────────────────────────
    gpio_init(PIN_ENC_CLK);
    gpio_set_dir(PIN_ENC_CLK, GPIO_IN);
    gpio_pull_up(PIN_ENC_CLK);
    gpio_init(PIN_ENC_DT);
    gpio_set_dir(PIN_ENC_DT, GPIO_IN);
    gpio_pull_up(PIN_ENC_DT);
    gpio_init(PIN_ENC_SW);
    gpio_set_dir(PIN_ENC_SW, GPIO_IN);
    gpio_pull_up(PIN_ENC_SW);
    enc_last_clk = gpio_get(PIN_ENC_CLK);
    enc_last_sw = gpio_get(PIN_ENC_SW);

    // ── Default key layout ────────────────────────────────────────────────
    setup_default_layout();

    // ── Initial LED draw ──────────────────────────────────────────────────
    led_self_test();
    refresh_leds();

    printf("=== READY — press a key! ===\n");

    // ── Main loop ─────────────────────────────────────────────────────────
    uint32_t last_ui_ms = to_ms_since_boot(get_absolute_time());
    uint32_t last_dbg_ms = 0;  // debug print every 1 s
    uint32_t last_disp_ms = 0; // OLED redraw throttle
    uint16_t last_drawn_keys = 0xFFFF;

    while (true)
    {
        // Fill audio if DMA interrupt requested it
        if (need_fill)
        {
            need_fill = false;
            int fill_buf = dma_play_idx ^ 1; // the buffer NOT currently playing
            fill_audio_buffer(audio_buf[fill_buf]);
        }

        // Throttle UI to ~333 Hz (3ms) for responsive button input
        uint32_t now = to_ms_since_boot(get_absolute_time());
        if (now - last_ui_ms < 3)
            continue;
        last_ui_ms = now;

        // ── Encoder ──────────────────────────────────────────────────
        bool enc_pressed;
        int rot = read_encoder(&enc_pressed);
        if (rot != 0)
        {
            current_waveform = (current_waveform + rot + 4) & 3;
            printf("Waveform: %d\n", current_waveform);
        }
        (void)enc_pressed; // GUI navigation not implemented yet

        // ── Pots ─────────────────────────────────────────────────────
        int vol_unused, vib_rate, vib_depth;
        read_pots(&vol_unused, &vib_rate, &vib_depth);
        // No volume pot connected: keep fixed at 2.55x (653 in Q8 format, 85% of previous 3.0x).
        master_gain_q8 = 653;
        lfo_inc = (uint32_t)((float)vib_rate * 16777216.0f / SAMPLE_RATE);
        lfo_depth = vib_depth;

        // ── Button scan (debounced press + release) ───────────────────
        uint16_t raw = mcp_read_buttons();

        // Debug: print raw button bits and encoder state once per second
        if (now - last_dbg_ms >= 1000)
        {
            last_dbg_ms = now;
            printf("BTN raw=0x%04X  ENC clk=%d dt=%d sw=%d  [TCA=%d TLV=%d OLED=%d@0x%02X]\n",
                   raw,
                   gpio_get(PIN_ENC_CLK),
                   gpio_get(PIN_ENC_DT),
                   gpio_get(PIN_ENC_SW),
                   dev_found_tca, dev_found_tlv, dev_found_oled, oled_addr);
        }

        for (int k = 0; k < 16; k++)
        {
            bool in_raw = (raw >> k) & 1;
            bool in_pressed = (pressed_keys >> k) & 1;

            if (in_raw)
            {
                press_count[k]++;
                release_count[k] = 0;
            }
            else
            {
                if (in_pressed)
                    release_count[k]++;
                press_count[k] = 0;
            }
        }

        uint16_t new_pressed = 0;
        for (int k = 0; k < 16; k++)
        {
            bool in_pressed = (pressed_keys >> k) & 1;
            if (press_count[k] >= PRESS_SCANS)
                new_pressed |= (1 << k);
            else if (in_pressed && release_count[k] < RELEASE_SCANS)
                new_pressed |= (1 << k); // within release debounce window
        }

        // ── React to changes ──────────────────────────────────────────
        if (new_pressed != pressed_keys)
        {
            uint16_t just_pressed = new_pressed & ~pressed_keys;
            uint16_t just_released = pressed_keys & ~new_pressed;
            pressed_keys = new_pressed;

            for (int k = 0; k < 16; k++)
            {
                if (just_released & (1 << k))
                {
                    if (key_assign[k].type == KEY_CHORD)
                        key_release(k);
                }
            }
            for (int k = 0; k < 16; k++)
            {
                if (just_pressed & (1 << k))
                {
                    KeyAssign *a = &key_assign[k];
                    if (a->type == KEY_DRUM)
                    {
                        // a->root is 0-3, maps to drum_samples array
                        if (a->root >= 0 && a->root < 4)
                        {
                            active_drum = drum_samples[a->root].data;
                            active_drum_len = drum_samples[a->root].len;
                        }
                        drum_pos = 0;
                    }
                    else
                    {
                        key_press(k);
                    }
                }
            }
            refresh_leds();
        }

        // ── OLED refresh (event-driven + slow keepalive) ──────────────
        // Full-screen I2C flushes are expensive; redraw on key changes.
        if (dev_found_oled && (pressed_keys != last_drawn_keys || now - last_disp_ms >= 500))
        {
            last_disp_ms = now;
            last_drawn_keys = pressed_keys;
            draw_grid();
            oled_flush();
        }
    }
}
